In [4]:
import numpy as np
a = np.arange(0,4)
a

array([0, 1, 2, 3])

In [3]:
b = np.arange(1,5)
b


array([1, 2, 3, 4])

In [5]:
np.add(a,b)


array([1, 3, 5, 7])

In [6]:
a+b

array([1, 3, 5, 7])

In [7]:
a>b


array([False, False, False, False])

In [8]:
a*b

array([ 0,  2,  6, 12])

In [9]:
a.shape

(4,)

In [11]:
a.shape = (2,2)
a

array([[0, 1],
       [2, 3]])

In [12]:
a.reshape((4,))

array([0, 1, 2, 3])

In [13]:
a

array([[0, 1],
       [2, 3]])

In [14]:
a.dtype

dtype('int64')

In [18]:
a = a.reshape((4,))
a

array([0, 1, 2, 3])

In [19]:
a[2:4]

array([2, 3])

In [20]:
a[1:4:2]

array([1, 3])

In [21]:
a[::-1]

array([3, 2, 1, 0])